title: 'Farmchinski Wedding'
default_lang: en
author:
  name: 'The Farmchinskis'
  email: rsvp@farminskiwedding.com
  url: 'http://farmchinskiwedding.com'
  gravatar: rsvp@farminskiwedding.com
  description: 'The Wedding of Hillary Farmer & Scott Kuchinski.  June 17, 2017.  Fiddle Lake Farm, Thompson, Pennsylvania.'
taxonomies:
  - category
  - tag
  - month
metadata:
  description: 'The Wedding of Hillary Farmer & Scott Kuchinski.'
summary:
  enabled: true
  format: short
  size: 100
  delimiter: '==='
  striptags: true
blog:
  route: ''
description: 'The Wedding of Hillary Farmer & Scott Kuchinski'
global_featured_image: featured.jpg
slider:
  -
    image: slide3.jpg
    title: 'A very delicious blog'
    url: '#'
  -
    image: slide1.jpg
    title: 'Duis autem'
    url: '#'
  -
    image: slide2.jpg
    title: 'Pumpkin recipe'
    url: '#'
menu:
  -
    url: error
    text: 'Error Page'
copyright: 'poop'
